apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment
spec:
  selector:
    matchLabels:
      app: assignment
  replicas: 1
  template:
    metadata:
      labels:
        app: assignment
    spec:
      containers:
      - name: assignment
        image: vinsdocker/k8s-deploy-assignment
        ports:
        - containerPort: 8080
          name: "app-port"
        env:
        - name: "spring.redis.host"
          value: "redis" 
        - name: "spring.redis.port"
          value: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6
        ports:
        - containerPort: 6379
          name: "redis-port"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379