apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  containers:
  - name: ubuntu
    image: ubuntu
    args: 
    - "sleep"
    - "3600"