apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    team: team-a
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    team: team-a 
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    team: team-a  
spec:
  containers:
  - name: nginx
    image: nginx